on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        CC: [gcc, clang]
        STD: [c99, c11, c17]
    env:
      make_options: 'CC=${{ matrix.CC }} STD=${{ matrix.STD }}'

    steps:
    - uses: actions/checkout@v2
    - run: make -n $make_options
    - run: make $make_options
    - run: make check $make_options
