on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        CC: [gcc, clang]
        STD: [c99, c11, c17]

    steps:
    - uses: actions/checkout@v2
    - run: make -v CC=${{ matrix.CC }} STD=${{ matrix.STD }}
    - run: make CC=${{ matrix.CC }} STD=${{ matrix.STD }}
    - run: make check CC=${{ matrix.CC }} STD=${{ matrix.STD }}
