on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        CC: [gcc, clang]
        STD: [c99, c11, c17]

        include:
        - CC: gcc
          STD: c17
          OPTIM: -O3
        - CC: clang
          STD: c17
          OPTIM: -O3

    env:
      make_options: 'CC=${{ matrix.CC }} STD=${{ matrix.STD }} OPTIM=${{ matrix.OPTIM }}' 

    steps:
    - uses: actions/checkout@v2
    - run: make -n $make_options
    - run: make $make_options
    - run: make check $make_options
