on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        CC: [gcc, clang]

    steps:
    - uses: actions/checkout@v2
    - run: make -n CC=${{ matrix.CC }}
    - run: make CC=${{ matrix.CC }}
    - run: make check CC=${{ matrix.CC }}
